version: '3'

services:
  web-app:
    build: .
    ports:
      - '8005:8005'
    volumes:
      - .:/project
    command: >
      sh -c "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:8005"
    environment:
      TZ: Europe/Moscow