# Generated by Django 4.2.13 on 2024-10-21 20:55
import datetime
from datetime import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
